### PR TITLE
Make portals generic in regards to level origin and destination

### PR DESCRIPTION
**Pull request by vascop**

### CODE REVIEW

**Comment by faitdivers** [comment]
[Test]
Can you provide a small test case where you insert a portal to go from map1 back to map0?

**Comment by vascop** [comment]
Sure, I'll post back

**Comment by vascop** [comment]
Upon further discussion the portal should be placed on the map by a JSON file and not hardcoded, once that's done this can be tested correctly.

**Comment by smiranda** [comment]
Approved.

As for the portal placement strategy, I totally agree. It should follow a scheme identical to the one used for bot placement, i.e., using some placeholder tiled id in the map json file. To this end, I recommend installing the Tiled map editor.

**Pull request merged**
